### ISSUE TITLE
where can i get the whole dataset?

### ISSUE THREAD

**Issue by hliu869** [kaaeaate/BoundaryLossProject#1]
Hello:
  thanks for your code , but when i want to run this code on my own PC, i don't know where i can get the dataset , i have tried to  search the dataset by Google, but did not get it,can you tell me the website or other more information?
best regrads.

**Comment by kaaeaate** [comment]
Hello!
We took 2 datasets (Hippocampus and Heart) from the website: http://medicaldecathlon.com
and then preprocessed them as in the original repository: https://github.com/LIVIAETS/boundary-loss/tree/master/preprocess
